project_id = "bcdgvdgndoatyccojsey"

[functions.health-chat]
verify_jwt = false

[functions.generate-vapid-keys]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false

[functions.send-medicine-reminders]
verify_jwt = false